import type { Metadata } from "next"
import SocialEngineClient from "./SocialEngineClient"

export const metadata: Metadata = {
  title: "Social Media Engine — AI Content for Instagram, LinkedIn, X & YouTube | JP Automations",
  description:
    "AI-powered social media content for Instagram, LinkedIn, X, and YouTube. Reels, carousels, posts, threads, outliers, and content plans — generated in seconds. Pay-as-you-go from £0.50/token.",
  alternates: {
    canonical: "https://www.jpautomations.co.uk/apps/social-engine",
  },
  openGraph: {
    title: "Social Media Engine — AI Content in Seconds | JP Automations",
    description:
      "Generate content for Instagram, LinkedIn, X, and YouTube with AI. Reels, carousels, posts, threads, and full content plans. Pay per use — no subscription.",
    url: "https://www.jpautomations.co.uk/apps/social-engine",
    images: [
      {
        url: "https://www.jpautomations.co.uk/og-image.png",
        width: 1200,
        height: 630,
        alt: "Social Media Engine — JP Automations",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Social Media Engine — AI Content for Every Platform",
    description:
      "Instagram reels, LinkedIn posts, X threads, YouTube outliers — all generated by AI. Pay per use, no subscription.",
  },
}

export default function SocialEnginePage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "SoftwareApplication",
            name: "Social Media Engine",
            applicationCategory: "BusinessApplication",
            operatingSystem: "Web",
            description:
              "AI-powered social media content engine for Instagram, LinkedIn, X, and YouTube. Generate reels, carousels, posts, threads, outliers, and content plans in seconds.",
            offers: {
              "@type": "AggregateOffer",
              priceCurrency: "GBP",
              lowPrice: "0.50",
              highPrice: "110",
              offerCount: "3",
            },
            creator: {
              "@type": "Organization",
              name: "JP Automations",
              url: "https://www.jpautomations.co.uk",
            },
            featureList: [
              "Instagram Reels",
              "Carousel Posts",
              "LinkedIn Posts",
              "X Threads & Tweets",
              "YouTube Outlier Detection",
              "Title Variants",
              "Content Plans",
              "Ad Creatives",
            ],
          }),
        }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            mainEntity: [
              {
                "@type": "Question",
                name: "Do I need design experience?",
                acceptedAnswer: {
                  "@type": "Answer",
                  text: "No. The entire process is prompt-based. Describe what you want in plain English and the AI generates the content.",
                },
              },
              {
                "@type": "Question",
                name: "Which platforms are supported?",
                acceptedAnswer: {
                  "@type": "Answer",
                  text: "Instagram, LinkedIn, X (Twitter), and YouTube. Each platform has dedicated tools optimised for its format and algorithm.",
                },
              },
              {
                "@type": "Question",
                name: "Can I use my own brand colours and style?",
                acceptedAnswer: {
                  "@type": "Answer",
                  text: "Yes. During onboarding you define your brand style, and all generated content will reflect it consistently.",
                },
              },
              {
                "@type": "Question",
                name: "How long does generation take?",
                acceptedAnswer: {
                  "@type": "Answer",
                  text: "Single images take 10–20 seconds. 7-slide carousels take 30–60 seconds. Reels take 1–2 minutes.",
                },
              },
              {
                "@type": "Question",
                name: "Do tokens expire?",
                acceptedAnswer: {
                  "@type": "Answer",
                  text: "No. Tokens never expire and work across all platforms — Instagram, LinkedIn, X, YouTube, SEO Blog, and every new app we release.",
                },
              },
              {
                "@type": "Question",
                name: "How do I get access?",
                acceptedAnswer: {
                  "@type": "Answer",
                  text: "Every engine is custom-built for your business. Book a 30-minute discovery call and we'll walk you through how it works, set up your brand profile, and get you generating content the same week.",
                },
              },
            ],
          }),
        }}
      />
      <SocialEngineClient />
    </>
  )
}
